export const SET_SESSION = 'SET_SESSION';
export const SET_USER = 'SET_USER';
export const RESET_SESSION = 'RESET_SESSION';

export const MERGE_ENTITIES = 'MERGE_ENTITIES';
export const SYNC_ENTITIES = 'SYNC_ENTITIES';

export const MERGE_GALLERIES = 'MERGE_GALLERIES';
export const MERGE_PHOTOS = 'MERGE_PHOTOS';

export const SET_REQUEST_IN_PROCESS = 'SET_REQUEST_IN_PROCESS';
export const SET_PAGINATE_LINK = 'SET_PAGINATE_LINK';

export const TOGGLE_SIDEMENU = 'TOGGLE_SIDEMENU'
